import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useRef, useEffect, RefObject, Ref } from 'react'

import AudioPlayer from '../components/AudioPlayer/AudioPlayer'
import Radio from '../components/Radio/Radio'

import radio from '../data/Radio/Radio_data.json'


import PlaylistProps from "../types/PlaylistProps";


export default function Home() {
  const [currentPlay, setCurrentPlay] = useState<number>(0);
  const [currentData , setCurrentData] = useState<PlaylistProps[]>(radio.data);
  const audioRef = useRef() as React.MutableRefObject<HTMLAudioElement>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {currentData.map((item, index) => (
            <Radio data={item} setCurrentData={setCurrentData} key={index} currentPlay={currentPlay} setCurrentPlay={setCurrentPlay} />
          ))}
        </div>
        <AudioPlayer currentData={currentData} currentPlay={currentPlay} setCurrentPlay={setCurrentPlay} forwardedRef={audioRef}/>
      </main>

      
    </div>
  )
}
