import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useRef, useEffect } from 'react'

import PlayLists from '../components/Playlists/Playlist'
import Radio from '../components/Radio/Radio'

import PlaylistProps from "../components/types/PlaylistProps";

export default function Home() {
  
  
  let data: PlaylistProps[] = [{
    id: 0,
    title: "RIM Pilgrim",
    artist: "RIM",
    album: "RIM Pilgrim",
    url: "/audio/RIM_Pilgrim.mp3",
    img: "img",
    
    },{
    id: 1,
    title: "Bury the Light",
    artist: "Casey Edwards/Victor Borba",
    album: "Bury the Light",
    url: "/audio/Bury the Light Vergils battle theme from Devil May Cry 5.mp3",
    img: "img",
  }]
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Radio data={data}/>
        <PlayLists data={data}/>
      </main>

      
    </div>
  )
}
